#! /bin/sh
if test $# -lt 2
then
   echo "usage:"
   echo "allnewnoad - <videodir>  [additional_noad_args]"
   echo "or"
   echo "allnewnoad nice <videodir>  [additional_noad_args]"
   exit -1
fi
${noadcmd:="$1"}
${vdir:="$2"}
shift 2
do find $vdir -follow -type d -name '*.rec' -exec ./noadifnew $* $noadcmd '{}' ';'

