#! /bin/sh
if test $# -lt 1
then
   echo "usage:"
   echo "allnoad <videodir> [additional_noad_args]"
   exit -1
fi
${vdir:=$1}
shift
find $vdir -follow -type d -name '*.rec' -exec ./noad $* - '{}' ';'

